Christoffer jakob/enc leaflet work
LauJosefsen/sw618f21 pull request #22
Opened 2021-03-23 08:03 UTC by JakobLund

Added leaflet map with support to show ENC cells

2021-03-23 09:09 UTC, Noobi99 approved these changes

2021-03-23 09:13 UTC, LauJosefsen requested changes

2021-03-23 09:13 UTC, LauJosefsen commented on src/db/init.sql
> +    cell_name varchar(50) primary key,
formatering

2021-03-23 09:13 UTC, LauJosefsen commented on src/db/init.sql
> +FROM points
fjern

2021-03-23 09:13 UTC, LauJosefsen commented on src/frontend/src/models/enc_cells.ts
> +    update: number,
mangler måske et lidt mere sigende navn eller en kommentar/docstring

2021-03-23 09:13 UTC, LauJosefsen commented on src/frontend/src/shared/points_on_map.tsx
> +                    <Marker position={L.latLng(points.latitude,points.longitude)} icon={defaultIcon}>
sæt en key på, ellerse vil react brokke sig/køre langsomt . key={points.id} fx

2021-03-23 09:13 UTC, LauJosefsen commented on src/frontend/src/shared/points_on_map.tsx
> +                        <Rectangle bounds={[[enc.north_limit, enc.west_limit], [enc.south_limit, enc.east_limit]]} pathOptions={{color: 'red'}}>
samme her, key key

2021-04-11 09:20 UTC, LauJosefsen requested changes

2021-04-11 09:20 UTC, LauJosefsen commented on src/api/app.py
> +@app.after_request  # blueprint can also be app~~
fjern kommentar

2021-04-11 09:20 UTC, LauJosefsen commented on src/api/data_management/course_cluster.py
> +        return 999999  # todo
Man kunne evt lave det sådan at hvis SOG ikke er sat på begge punkter, så er afstanden mellem dem 0, og hvis det er sat på det ene, men ikke det andet, så er det 99999

2021-04-11 09:27 UTC, JakobLund commented on src/api/controller/ais_data_controller.py
> +    data = ais_data_service.new_cluster()
rename "new_cluster"

2021-04-11 10:25 UTC, LauJosefsen approved these changes

2021-04-11 10:34 UTC, merged